language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - addon-google_apis_x86-google-21
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-google_play_services
  - sys-img-armeabi-v7a-android-21
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script: "./gradlew testDebugUnitTest"
branches:
- travisci
- development
notifications:
  slack:
    rooms:
      secure: VlSszhvKkGz1Yea/xuunE+BQzmVUkQttLwXXj+KcMBA1ZsnNb1t53Ugj7cOIPc2fL62AKVaN35yP33STvdBAcpiG/hp4u2UtF68m68q9ghNwrYoP9fzGNt5Ds3M/975Y7VE56RFMzGCC6vFCghViXAhr5vfn/EQl+vJSSm8s6bzTNdVF2zNHOKVKH/fLzcFNvsa4xGw54lQMgBlAPDzkFsVR3DV0EL+YDgjIugrywUI2vPxdDw2tUH+pJTgZd/4Xun93FCLxnYE3+fYqBSKjYxGxQtv1ujUfL3zD57exi6Nr1rrvLFhRvnj6hqE70p7dXTR06jhGokx8tnQLVBzdcKkIbDZke9bmMXdkipRMjnLkodZw1enVJzsk18/JiHJZWN7EEQB6zT6tqkzgDqL5F5l7m17PMtSt+ZtC4vqXtquZrLx/hgCU0afqLxelom7cePGrA+sAmTolKGKzKYOQCxDxfPDGLLAM2mRec5NvlpipRnyHjbb1mwoN7Fwp9tKqqYkaq4URGOZct9pOGRoJYkViSicI2gViNs09++pBK7gpwUpfUqeIcgg0jDfgV/EYlvoP/CPhGczaoyBfu9YfNmXQb8mjl3rS1qQRvfjt9cFLoBGGYtC1YsCccV5mDY/omgRuIArVWRI5RrsCrKhwQove0DrEu8k3sfpbhnnpWY8=
    template:
    - 'Test run completed for %{repository}/*%{branch}*: <%{build_url}|%{message}> Run duration: %{elapsed_time} '
